### ISSUE TITLE
--spliced not supported? (Question)

### ISSUE THREAD

**Issue by MrKevinDC** [wdecoster/cramino#13]
Is the `--spliced` supported?, I tried to use but I keep getting this error

> error: Found argument '--spliced' which wasn't expected, or isn't valid in this context
> If you tried to supply `--spliced` as a value rather than a flag, use `-- --spliced`

Plus, it no longer shows in the command line help (`-h`) message.

**Comment by wdecoster** [comment]
Weird! Which version are you using and how did you install it?

**Comment by MrKevinDC** [comment]
I am using the latest 0.9.7, installed via the Linux binaries.

**Comment by wdecoster** [comment]
Should be in v0.9.9, which I just released. Let me know if there is something else I can help with :)
