### ISSUE TITLE
Does cramino support unmapped bam?

### ISSUE THREAD

**Issue by ymcki** [wdecoster/cramino#15]
It works with the cram file I have but crashes when I give it an unmapped bam:

~/utils/cramino -t 4 ABC.ubam --arrow ABC.unmapped.feather
File name       ABC.ubam
[2023-07-21T04:19:31Z ERROR cramino] Not enough reads to calculate metrics!
thread 'main' panicked at 'explicit panic', src/main.rs:155:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

By the way, is it possible to also output number of mapped bases and unmapped bases for aligned cram/bam?

**Comment by wdecoster** [comment]
Indeed, cramino does not support ubam (for now).  I will think about your other suggestion regarding number of (un)mapped bases.

**Comment by wdecoster** [comment]
Cramino v0.10.0 has support for ubam files, with `--ubam`.  The number of mapped bases is not yet supported and more likely would be provided as the fraction of mapped _reads_ in a future version.
