### ISSUE TITLE
Multiple file inputs

### ISSUE THREAD

**Issue by Shians** [wdecoster/cramino#27]
It would be useful to be able to put in multiple files as inputs and iterate through them to populate the table.

**Comment by wdecoster** [comment]
Do you mean you want to combine the multiple files into one report, as if they were one file? You could probably do that with `samtools cat` and pipe the output into cramino, as cramino can read from stdin.

**Comment by Shians** [comment]
I mean the stats would be reported for each file as additional columns in the output. Just so all the results can live in a single file without additional manipulation.

**Comment by wdecoster** [comment]
Ah. No, that is not something that I plan to implement. I would suggest writing a (python or other) script to gather multiple cramino files.
